cmake_minimum_required(VERSION 3.21)
# Tool-protocol fixtures only: these JSON files are NOT real Mach-O binaries.
set(args)
set(after FALSE)
math(EXPR last "${CMAKE_ARGC} - 1")
foreach(index RANGE 0 ${last})
  set(value "${CMAKE_ARGV${index}}")
  if(after)
    list(APPEND args "${value}")
  elseif(value STREQUAL "--")
    set(after TRUE)
  endif()
endforeach()
list(GET args 0 action)
if(TOOL STREQUAL "file")
  list(GET args 1 image)
  file(READ "${image}" doc)
  string(JSON format ERROR_VARIABLE error GET "${doc}" format)
  if(NOT error AND format STREQUAL "Mach-O")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "Mach-O fixture")
  else()
    execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "ASCII text")
  endif()
elseif(TOOL STREQUAL "otool")
  list(GET args 1 arch)
  list(GET args 3 image)
  file(READ "${image}" doc)
  string(JSON count LENGTH "${doc}" slices "${arch}")
  set(output "${image} (architecture ${arch}):\n")
  if(count GREATER 0)
    math(EXPR last "${count} - 1")
    foreach(index RANGE 0 ${last})
      string(JSON path GET "${doc}" slices "${arch}" ${index})
      string(APPEND output "Load command ${index}\n          cmd LC_RPATH\n      cmdsize 64\n         path ${path} (offset 12)\n")
    endforeach()
  endif()
  execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "${output}")
elseif(TOOL STREQUAL "lipo")
  if(action STREQUAL "-archs")
    list(GET args 1 image)
    file(READ "${image}" doc)
    string(JSON count LENGTH "${doc}" slices)
    math(EXPR last "${count} - 1")
    set(arches)
    foreach(index RANGE 0 ${last})
      string(JSON arch MEMBER "${doc}" slices ${index})
      list(APPEND arches "${arch}")
    endforeach()
    list(JOIN arches " " output)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "${output}")
  elseif(action STREQUAL "-thin")
    list(GET args 1 arch)
    list(GET args 2 image)
    list(GET args 4 target)
    file(READ "${image}" doc)
    string(JSON paths GET "${doc}" slices "${arch}")
    string(JSON doc SET "${doc}" slices "{}")
    string(JSON doc SET "${doc}" slices "${arch}" "${paths}")
    file(WRITE "${target}" "${doc}")
  elseif(action STREQUAL "-create")
    list(REMOVE_AT args 0)
    set(doc "{\"format\":\"Mach-O\",\"slices\":{}}")
    set(next_target FALSE)
    foreach(image IN LISTS args)
      if(next_target)
        set(target "${image}")
        break()
      elseif(image STREQUAL "-output")
        set(next_target TRUE)
        continue()
      endif()
      file(READ "${image}" slice)
      string(JSON arch MEMBER "${slice}" slices 0)
      string(JSON paths GET "${slice}" slices "${arch}")
      string(JSON doc SET "${doc}" slices "${arch}" "${paths}")
    endforeach()
    file(WRITE "${target}" "${doc}")
  else()
    message(FATAL_ERROR "Unknown lipo action")
  endif()
elseif(TOOL STREQUAL "install_name_tool")
  list(GET args 1 wanted)
  list(GET args 2 image)
  file(READ "${image}" doc)
  string(JSON arch MEMBER "${doc}" slices 0)
  string(JSON count LENGTH "${doc}" slices "${arch}")
  string(JSON deletion ERROR_VARIABLE unused GET "${doc}" delete_mode)
  set(paths "[]")
  set(size 0)
  set(removed FALSE)
  if(count GREATER 0)
    math(EXPR last "${count} - 1")
    foreach(index RANGE 0 ${last})
      string(JSON path GET "${doc}" slices "${arch}" ${index})
      if(action STREQUAL "-delete_rpath" AND path STREQUAL wanted AND (NOT removed OR deletion STREQUAL "all"))
        set(removed TRUE)
        continue()
      endif()
      string(JSON paths SET "${paths}" ${size} "\"${path}\"")
      math(EXPR size "${size} + 1")
    endforeach()
  endif()
  if(action STREQUAL "-add_rpath")
    string(JSON paths SET "${paths}" ${size} "\"${wanted}\"")
  elseif(NOT removed)
    message(FATAL_ERROR "Missing RPATH requested for removal")
  endif()
  string(JSON doc SET "${doc}" slices "${arch}" "${paths}")
  file(WRITE "${image}" "${doc}")
else()
  message(FATAL_ERROR "Unknown fake Mach-O tool")
endif()
