cmake_minimum_required(VERSION 3.21)
include("${CMAKE_CURRENT_LIST_DIR}/../cmake/GaugeBundle.cmake")
if(NOT DEFINED SOURCE_DIR OR NOT DEFINED WORK_DIR)
  message(FATAL_ERROR "SOURCE_DIR and dedicated WORK_DIR required")
endif()
omatrack_verify_gauge_bundle("${SOURCE_DIR}")
omatrack_gauge_bundle_files(paths)
file(MAKE_DIRECTORY "${WORK_DIR}")
foreach(path IN LISTS paths)
  get_filename_component(parent "${WORK_DIR}/${path}" DIRECTORY)
  file(MAKE_DIRECTORY "${parent}")
  file(COPY_FILE "${SOURCE_DIR}/${path}" "${WORK_DIR}/${path}")
endforeach()
file(COPY_FILE "${SOURCE_DIR}/bundle.json" "${WORK_DIR}/bundle.json")
omatrack_verify_gauge_bundle("${WORK_DIR}")
function(expect_rejection label)
  execute_process(COMMAND "${CMAKE_COMMAND}" -DMODE=verify "-DBUNDLE_DIR=${WORK_DIR}"
    -P "${CMAKE_CURRENT_LIST_DIR}/../scripts/gauge-bundle.cmake"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(result EQUAL 0)
    message(FATAL_ERROR "Bundle verifier accepted ${label}")
  endif()
endfunction()
file(REMOVE "${WORK_DIR}/licenses/detectors/NOTICE")
expect_rejection("missing license/notice")
file(COPY_FILE "${SOURCE_DIR}/licenses/detectors/NOTICE" "${WORK_DIR}/licenses/detectors/NOTICE")
file(APPEND "${WORK_DIR}/bundle.json" "\nmodified\n")
expect_rejection("modified package-owned manifest")
file(COPY_FILE "${SOURCE_DIR}/bundle.json" "${WORK_DIR}/bundle.json")
file(APPEND "${WORK_DIR}/detectors/tiny-v2/gauge-detector.onnx" "x")
expect_rejection("modified model bytes")
message(STATUS "Offline bundle missing-notice/manifest/model corruption guards PASS")
