cmake_minimum_required(VERSION 3.21)
# Exercise the packaging control flow with deterministic tool-protocol mocks.
# Native Mach-O/dyld/signing acceptance still belongs to the macOS dry run.
if(NOT DEFINED WORK_DIR)
  message(FATAL_ERROR "Dedicated WORK_DIR required")
endif()
set(bundle "${WORK_DIR}/App.app")
file(MAKE_DIRECTORY "${bundle}/Contents/MacOS" "${bundle}/Contents/Frameworks" "${bundle}/Contents/Resources/models")
set(mock "${CMAKE_CURRENT_LIST_DIR}/FakeMachOTool.cmake")
set(script "${CMAKE_CURRENT_LIST_DIR}/../packaging/macos/rpaths.cmake")
function(run mode succeeds)
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DMODE=${mode}" "-DBUNDLE_DIR=${bundle}"
    "-DMACHO_FILE=${CMAKE_COMMAND};-DTOOL=file;-P;${mock};--"
    "-DMACHO_OTOOL=${CMAKE_COMMAND};-DTOOL=otool;-P;${mock};--"
    "-DMACHO_LIPO=${CMAKE_COMMAND};-DTOOL=lipo;-P;${mock};--"
    "-DMACHO_INSTALL_NAME_TOOL=${CMAKE_COMMAND};-DTOOL=install_name_tool;-P;${mock};--"
    -P "${script}" WORKING_DIRECTORY "${WORK_DIR}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(succeeds AND NOT result EQUAL 0)
    message(FATAL_ERROR "RPATH ${mode} failed: ${output}\n${error}")
  elseif(NOT succeeds AND result EQUAL 0)
    message(FATAL_ERROR "RPATH ${mode} accepted invalid fixture")
  endif()
  if(ARGC GREATER 2)
    string(FIND "${error}" "${ARGV2}" match)
    if(match LESS 0)
      message(FATAL_ERROR "RPATH ${mode} failed for the wrong reason: ${error}")
    endif()
  endif()
endfunction()
set(app "${bundle}/Contents/MacOS/Omatrack")
set(fat "${bundle}/Contents/Frameworks/libmpv.2.dylib")
set(thin "${bundle}/Contents/Frameworks/libother.dylib")
file(WRITE "${app}" [=[{"format":"Mach-O","slices":{"arm64":["@executable_path/../Frameworks/"],"x86_64":["@executable_path/../Frameworks/"]}}]=])
file(WRITE "${fat}" [=[{"format":"Mach-O","slices":{"arm64":["@executable_path/../Frameworks/","@loader_path","@executable_path/../Frameworks/"],"x86_64":["@loader_path","@executable_path/../Frameworks/"]}}]=])
file(WRITE "${thin}" [=[{"format":"Mach-O","delete_mode":"all","slices":{"arm64":["@executable_path/../Frameworks/","@loader_path/Sibling Space","@executable_path/../Frameworks/"]}}]=])
file(WRITE "${bundle}/Contents/Resources/models/NOTICE" "non-code model notice")
file(SHA256 "${app}" app_before)
run(verify FALSE)
run(dedupe TRUE)
run(verify TRUE)
file(SHA256 "${app}" app_after)
if(NOT app_before STREQUAL app_after)
  message(FATAL_ERROR "One RPATH per architecture was mistaken for a duplicate")
endif()
file(READ "${fat}" doc)
foreach(arch arm64 x86_64)
  string(JSON count LENGTH "${doc}" slices "${arch}")
  if(NOT count EQUAL 2)
    message(FATAL_ERROR "Slice lost distinct RPATHs")
  endif()
endforeach()
string(JSON first GET "${doc}" slices arm64 0)
string(JSON second GET "${doc}" slices x86_64 0)
if(NOT first STREQUAL "@executable_path/../Frameworks/" OR NOT second STREQUAL "@loader_path")
  message(FATAL_ERROR "Original per-slice RPATH search order changed")
endif()
file(READ "${thin}" doc)
string(JSON count LENGTH "${doc}" slices arm64)
string(JSON spaced GET "${doc}" slices arm64 1)
if(NOT count EQUAL 2 OR NOT spaced STREQUAL "@loader_path/Sibling Space")
  message(FATAL_ERROR "Distinct path containing spaces was lost")
endif()
file(SHA256 "${fat}" first_pass)
run(dedupe TRUE)
file(SHA256 "${fat}" second_pass)
if(NOT first_pass STREQUAL second_pass)
  message(FATAL_ERROR "RPATH normalization is not idempotent")
endif()
set(bad "${bundle}/Contents/Frameworks/developer.dylib")
file(WRITE "${bad}" [=[{"format":"Mach-O","slices":{"arm64":["/opt/homebrew/lib","@loader_path"]}}]=])
file(SHA256 "${bad}" bad_before)
run(verify FALSE)
run(dedupe FALSE)
file(SHA256 "${bad}" bad_after)
if(NOT bad_before STREQUAL bad_after)
  message(FATAL_ERROR "Developer path was silently deleted to hide a packaging error")
endif()
file(REMOVE "${bad}")
# Actual Qt SDK ../../../lib relocation after flattening into Contents/PlugIns.
set(plugin "${bundle}/Contents/PlugIns/libeffectsplugin.dylib")
set(qt "${bundle}/Contents/Frameworks/QtCore.framework/Versions/A/QtCore")
set(qt_binary [=[{"format":"Mach-O","slices":{"arm64":[],"x86_64":[]}}]=])
file(WRITE "${qt}" "${qt_binary}")
set(qt_plugin [=[{"format":"Mach-O","id":"@rpath/own-id-is-not-a-dependency","slices":{"arm64":["/usr/lib","@loader_path/../../../lib","@loader_path"],"x86_64":["@loader_path","@loader_path/../../../lib","/System/Library/Frameworks"]},"dependencies":{"arm64":["@rpath/QtCore.framework/Versions/A/QtCore","/usr/lib/libSystem.B.dylib","@executable_path/../Frameworks/libother.dylib"],"x86_64":["@rpath/QtCore.framework/Versions/A/QtCore","/System/Library/Frameworks/Foundation.framework/Foundation"]}}]=])
file(WRITE "${plugin}" "${qt_plugin}")
run(verify FALSE "LC_RPATH escapes")
run(dedupe TRUE)
run(verify TRUE)
file(READ "${plugin}" relocated)
foreach(arch arm64 x86_64)
  string(JSON path GET "${relocated}" slices "${arch}" 1)
  string(JSON count LENGTH "${relocated}" slices "${arch}")
  if(NOT path STREQUAL "@executable_path/../Frameworks" OR NOT count EQUAL 3)
    message(FATAL_ERROR "Qt SDK relocation did not replace only the stale slot")
  endif()
endforeach()
string(JSON first GET "${relocated}" slices arm64 0)
string(JSON last GET "${relocated}" slices arm64 2)
if(NOT first STREQUAL "/usr/lib" OR NOT last STREQUAL "@loader_path")
  message(FATAL_ERROR "Qt relocation changed valid system/internal path order")
endif()
file(SHA256 "${app}" app_after)
if(NOT app_before STREQUAL app_after)
  message(FATAL_ERROR "Qt relocation modified an already-valid image")
endif()
file(SHA256 "${plugin}" first_pass)
run(dedupe TRUE)
file(SHA256 "${plugin}" second_pass)
if(NOT first_pass STREQUAL second_pass)
  message(FATAL_ERROR "Qt relocation is not idempotent")
endif()
function(plugin_must_fail expected)
  file(SHA256 "${plugin}" before)
  run(dedupe FALSE "${expected}")
  file(SHA256 "${plugin}" after)
  if(NOT before STREQUAL after)
    message(FATAL_ERROR "Dependency proof failed after modifying the original plugin")
  endif()
endfunction()
# Missing dependency in the SECOND slice must fail before either slice is rewritten.
string(JSON missing SET "${qt_plugin}" dependencies x86_64 2 "\"@rpath/libMissing.dylib\"")
file(WRITE "${plugin}" "${missing}")
plugin_must_fail("Missing/ambiguous dependency")
# Two retained search roots resolving the same install name differently are ambiguous.
file(WRITE "${bundle}/Contents/PlugIns/Alt/QtCore.framework/Versions/A/QtCore" "${qt_binary}")
string(JSON ambiguous SET "${qt_plugin}" slices arm64 3 "\"@loader_path/Alt\"")
file(WRITE "${plugin}" "${ambiguous}")
plugin_must_fail("Missing/ambiguous dependency")
# Merely resembling a Qt SDK RPATH is not enough for a non-Qt plugin.
string(JSON nonqt SET "${qt_plugin}" dependencies "{\"arm64\":[\"@rpath/libother.dylib\"],\"x86_64\":[\"@rpath/libother.dylib\"]}")
file(WRITE "${plugin}" "${nonqt}")
plugin_must_fail("requires a resolved bundled Qt framework")
# A non-system direct dependency must also stay inside actual Contents.
file(WRITE "${WORK_DIR}/external.dylib" "${qt_binary}")
string(JSON external SET "${qt_plugin}" dependencies arm64 3 "\"@executable_path/../../../external.dylib\"")
file(WRITE "${plugin}" "${external}")
plugin_must_fail("dependency escapes Contents")
file(REMOVE "${plugin}")
# Qt-bearing images outside PlugIns are not eligible for this targeted policy.
file(WRITE "${bad}" "${qt_plugin}")
file(SHA256 "${bad}" before)
run(dedupe FALSE "only allowed for in-bundle PlugIns")
file(SHA256 "${bad}" after)
if(NOT before STREQUAL after)
  message(FATAL_ERROR "Non-eligible image was modified")
endif()
file(REMOVE "${bad}")
file(WRITE "${plugin}" "${relocated}")
run(verify TRUE)
message(STATUS "RPATH protocol tests PASS: fat/thin, ordered deduplication, proven Qt SDK relocation, missing/ambiguous/external/nonQt/notPlugIns rejection; NOT native Mach-O proof")
