cmake_minimum_required(VERSION 3.21)
# Exercise the packaging control flow with deterministic tool-protocol mocks.
# Native Mach-O/dyld/signing acceptance still belongs to the macOS dry run.
if(NOT DEFINED WORK_DIR)
  message(FATAL_ERROR "Dedicated WORK_DIR required")
endif()
set(bundle "${WORK_DIR}/App.app")
file(MAKE_DIRECTORY "${bundle}/Contents/MacOS" "${bundle}/Contents/Frameworks" "${bundle}/Contents/Resources/models")
set(mock "${CMAKE_CURRENT_LIST_DIR}/FakeMachOTool.cmake")
set(script "${CMAKE_CURRENT_LIST_DIR}/../packaging/macos/rpaths.cmake")
function(run mode succeeds)
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DMODE=${mode}" "-DBUNDLE_DIR=${bundle}"
    "-DMACHO_FILE=${CMAKE_COMMAND};-DTOOL=file;-P;${mock};--"
    "-DMACHO_OTOOL=${CMAKE_COMMAND};-DTOOL=otool;-P;${mock};--"
    "-DMACHO_LIPO=${CMAKE_COMMAND};-DTOOL=lipo;-P;${mock};--"
    "-DMACHO_INSTALL_NAME_TOOL=${CMAKE_COMMAND};-DTOOL=install_name_tool;-P;${mock};--"
    -P "${script}" WORKING_DIRECTORY "${WORK_DIR}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(succeeds AND NOT result EQUAL 0)
    message(FATAL_ERROR "RPATH ${mode} failed: ${output}\n${error}")
  elseif(NOT succeeds AND result EQUAL 0)
    message(FATAL_ERROR "RPATH ${mode} accepted invalid fixture")
  endif()
endfunction()
set(app "${bundle}/Contents/MacOS/Omatrack")
set(fat "${bundle}/Contents/Frameworks/libmpv.2.dylib")
set(thin "${bundle}/Contents/Frameworks/libother.dylib")
file(WRITE "${app}" [=[{"format":"Mach-O","slices":{"arm64":["@executable_path/../Frameworks/"],"x86_64":["@executable_path/../Frameworks/"]}}]=])
file(WRITE "${fat}" [=[{"format":"Mach-O","slices":{"arm64":["@executable_path/../Frameworks/","@loader_path","@executable_path/../Frameworks/"],"x86_64":["@loader_path","@executable_path/../Frameworks/"]}}]=])
file(WRITE "${thin}" [=[{"format":"Mach-O","delete_mode":"all","slices":{"arm64":["@executable_path/../Frameworks/","@loader_path/Sibling Space","@executable_path/../Frameworks/"]}}]=])
file(WRITE "${bundle}/Contents/Resources/models/NOTICE" "non-code model notice")
file(SHA256 "${app}" app_before)
run(verify FALSE)
run(dedupe TRUE)
run(verify TRUE)
file(SHA256 "${app}" app_after)
if(NOT app_before STREQUAL app_after)
  message(FATAL_ERROR "One RPATH per architecture was mistaken for a duplicate")
endif()
file(READ "${fat}" doc)
foreach(arch arm64 x86_64)
  string(JSON count LENGTH "${doc}" slices "${arch}")
  if(NOT count EQUAL 2)
    message(FATAL_ERROR "Slice lost distinct RPATHs")
  endif()
endforeach()
string(JSON first GET "${doc}" slices arm64 0)
string(JSON second GET "${doc}" slices x86_64 0)
if(NOT first STREQUAL "@executable_path/../Frameworks/" OR NOT second STREQUAL "@loader_path")
  message(FATAL_ERROR "Original per-slice RPATH search order changed")
endif()
file(READ "${thin}" doc)
string(JSON count LENGTH "${doc}" slices arm64)
string(JSON spaced GET "${doc}" slices arm64 1)
if(NOT count EQUAL 2 OR NOT spaced STREQUAL "@loader_path/Sibling Space")
  message(FATAL_ERROR "Distinct path containing spaces was lost")
endif()
file(SHA256 "${fat}" first_pass)
run(dedupe TRUE)
file(SHA256 "${fat}" second_pass)
if(NOT first_pass STREQUAL second_pass)
  message(FATAL_ERROR "RPATH normalization is not idempotent")
endif()
set(bad "${bundle}/Contents/Frameworks/developer.dylib")
file(WRITE "${bad}" [=[{"format":"Mach-O","slices":{"arm64":["/opt/homebrew/lib","@loader_path"]}}]=])
file(SHA256 "${bad}" bad_before)
run(verify FALSE)
run(dedupe FALSE)
file(SHA256 "${bad}" bad_after)
if(NOT bad_before STREQUAL bad_after)
  message(FATAL_ERROR "Developer path was silently deleted to hide a packaging error")
endif()
file(REMOVE "${bad}")
message(STATUS "RPATH protocol tests PASS: fat/thin, one/all deletion, distinct order/spaces, idempotence, developer rejection; NOT native Mach-O proof")
