cmake_minimum_required(VERSION 3.21)
# After macdeployqt/dylibbundler and before final signing. Deduplicate RPATHs
# and narrowly relocate proven Qt SDK plugin lib-search paths. Other distinct
# paths and their order are preserved. Fat slices are handled independently.
if(NOT MODE MATCHES "^(verify|dedupe)$" OR NOT IS_DIRECTORY "${BUNDLE_DIR}/Contents")
  message(FATAL_ERROR "Use -DMODE=verify|dedupe -DBUNDLE_DIR=/path/to/App.app")
endif()
foreach(tool FILE OTOOL LIPO INSTALL_NAME_TOOL)
  if(NOT DEFINED MACHO_${tool})
    string(TOLOWER "${tool}" name)
    find_program(MACHO_${tool} NAMES "${name}" REQUIRED)
  endif()
endforeach()
file(REAL_PATH "${BUNDLE_DIR}" bundle)
file(REAL_PATH "${bundle}/Contents" contents)

function(read_rpaths image arch output)
  execute_process(COMMAND ${MACHO_OTOOL} -arch "${arch}" -l "${image}"
    RESULT_VARIABLE result OUTPUT_VARIABLE listing ERROR_VARIABLE error)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "otool failed for ${image} (${arch}): ${error}")
  endif()
  string(REPLACE "\n" ";" lines "${listing}")
  set(paths)
  set(wanted FALSE)
  foreach(line IN LISTS lines)
    string(STRIP "${line}" line)
    if(line MATCHES "^cmd[ \t]+LC_RPATH$")
      set(wanted TRUE)
    elseif(wanted AND line MATCHES "^path (.*) \\(offset [0-9]+\\)$")
      list(APPEND paths "${CMAKE_MATCH_1}")
      set(wanted FALSE)
    endif()
  endforeach()
  if(wanted)
    message(FATAL_ERROR "Incomplete LC_RPATH in ${image} (${arch})")
  endif()
  set(${output} "${paths}" PARENT_SCOPE)
endfunction()

function(check_path path image)
  if(path MATCHES "^/System/Library(/|$)" OR path MATCHES "^/usr/lib(/|$)")
    return()
  elseif(path MATCHES "^@executable_path(/|$)")
    string(REGEX REPLACE "^@executable_path" "${contents}/MacOS" resolved "${path}")
  elseif(path MATCHES "^@loader_path(/|$)")
    get_filename_component(loader "${image}" DIRECTORY)
    string(REGEX REPLACE "^@loader_path" "${loader}" resolved "${path}")
  else()
    # Never hide a developer path by deleting it. Absolute paths into the
    # current staging tree are not relocatable either.
    message(FATAL_ERROR "Nonportable/developer LC_RPATH '${path}' in ${image}")
  endif()
  file(REAL_PATH "${resolved}" resolved)
  file(RELATIVE_PATH relative "${contents}" "${resolved}")
  if(IS_ABSOLUTE "${relative}" OR relative MATCHES "^\\.\\.(/|$)")
    message(FATAL_ERROR "LC_RPATH escapes actual package Contents: '${path}' in ${image}")
  endif()
endfunction()

# Used only by dependency proof after every proposed RPATH passed check_path.
function(search_directory path image output)
  get_filename_component(loader "${image}" DIRECTORY)
  string(REPLACE "@loader_path" "${loader}" resolved "${path}")
  string(REPLACE "@executable_path" "${contents}/MacOS" resolved "${resolved}")
  file(REAL_PATH "${resolved}" resolved)
  set(${output} "${resolved}" PARENT_SCOPE)
endfunction()

function(prove_qt_dependencies image arch planned)
  execute_process(COMMAND ${MACHO_OTOOL} -arch "${arch}" -l "${image}"
    RESULT_VARIABLE result OUTPUT_VARIABLE listing ERROR_VARIABLE error)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Cannot inspect plugin dependencies: ${image} (${arch}): ${error}")
  endif()
  string(REPLACE "\n" ";" lines "${listing}")
  set(dependencies)
  set(wanted FALSE)
  foreach(line IN LISTS lines)
    string(STRIP "${line}" line)
    if(line MATCHES "^cmd[ \t]+LC_(LOAD_DYLIB|LOAD_WEAK_DYLIB|REEXPORT_DYLIB|LAZY_LOAD_DYLIB|LOAD_UPWARD_DYLIB)$")
      if(wanted)
        message(FATAL_ERROR "Incomplete dynamic dependency in ${image} (${arch})")
      endif()
      set(wanted TRUE)
    elseif(line MATCHES "^cmd[ \t]+")
      if(wanted)
        message(FATAL_ERROR "Incomplete dynamic dependency in ${image} (${arch})")
      endif()
    elseif(wanted AND line MATCHES "^name (.*) \\(offset [0-9]+\\)$")
      list(APPEND dependencies "${CMAKE_MATCH_1}")
      set(wanted FALSE)
    endif()
  endforeach()
  if(wanted)
    message(FATAL_ERROR "Incomplete dynamic dependency in ${image} (${arch})")
  endif()
  set(found_qt FALSE)
  file(REAL_PATH "${contents}/Frameworks" frameworks)
  foreach(dependency IN LISTS dependencies)
    if(dependency MATCHES "^/System/Library(/|$)" OR dependency MATCHES "^/usr/lib(/|$)")
      continue() # dyld shared-cache/system dependencies need not be physical files.
    endif()
    set(candidates)
    if(dependency MATCHES "^@rpath/(.+)$")
      set(tail "${CMAKE_MATCH_1}")
      foreach(path IN LISTS planned)
        search_directory("${path}" "${image}" directory)
        list(APPEND candidates "${directory}/${tail}")
      endforeach()
    elseif(dependency MATCHES "^@(loader_path|executable_path)/")
      search_directory("${dependency}" "${image}" direct)
      list(APPEND candidates "${direct}")
    else()
      message(FATAL_ERROR "Non-system dependency is not package-relative: '${dependency}' in ${image}")
    endif()
    set(matches)
    foreach(candidate IN LISTS candidates)
      if(NOT EXISTS "${candidate}" OR IS_DIRECTORY "${candidate}")
        continue()
      endif()
      file(REAL_PATH "${candidate}" actual)
      file(RELATIVE_PATH relative "${contents}" "${actual}")
      if(IS_ABSOLUTE "${relative}" OR relative MATCHES "^\\.\\.(/|$)")
        message(FATAL_ERROR "Non-system dependency escapes Contents: '${dependency}' in ${image}")
      endif()
      list(APPEND matches "${actual}")
    endforeach()
    list(REMOVE_DUPLICATES matches) # Multiple paths to the same symlink target are not ambiguous.
    list(LENGTH matches count)
    if(NOT count EQUAL 1)
      message(FATAL_ERROR "Missing/ambiguous dependency '${dependency}' in ${image} (${arch}): ${matches}")
    endif()
    list(GET matches 0 actual)
    execute_process(COMMAND ${MACHO_FILE} -b "${actual}" RESULT_VARIABLE result OUTPUT_VARIABLE kind)
    if(NOT result EQUAL 0 OR NOT kind MATCHES "Mach-O")
      message(FATAL_ERROR "Bundled dynamic dependency is not Mach-O: ${actual}")
    endif()
    file(RELATIVE_PATH relative "${frameworks}" "${actual}")
    if(dependency MATCHES "(^|/)Qt[^/]*\\.framework/" AND
       NOT IS_ABSOLUTE "${relative}" AND NOT relative MATCHES "^\\.\\.(/|$)")
      set(found_qt TRUE)
    endif()
  endforeach()
  if(NOT found_qt)
    message(FATAL_ERROR "SDK RPATH relocation requires a resolved bundled Qt framework: ${image}")
  endif()
endfunction()

function(plan_rpaths image arch original output)
  # Qt SDK plugins/QML modules search ../../lib through ../../../../../lib.
  # These become stale after macdeployqt flattens them into Contents/PlugIns.
  set(sdk_paths "@loader_path/../../lib" "@loader_path/../../../lib"
                "@loader_path/../../../../lib" "@loader_path/../../../../../lib")
  set(replacement "@executable_path/../Frameworks")
  if("@executable_path/../Frameworks/" IN_LIST original)
    set(replacement "@executable_path/../Frameworks/")
  endif()
  set(planned)
  set(relocated FALSE)
  foreach(path IN LISTS original)
    if(MODE STREQUAL "dedupe" AND path IN_LIST sdk_paths)
      search_directory("${path}" "${image}" resolved)
      file(RELATIVE_PATH relative "${contents}" "${resolved}")
      if(IS_ABSOLUTE "${relative}" OR relative MATCHES "^\\.\\.(/|$)")
        file(RELATIVE_PATH plugin "${contents}" "${image}")
        if(NOT plugin MATCHES "^PlugIns/.+\\.dylib$")
          message(FATAL_ERROR "Qt SDK RPATH relocation is only allowed for in-bundle PlugIns dylibs: ${image}")
        endif()
        set(path "${replacement}")
        set(relocated TRUE)
      endif()
    endif()
    check_path("${path}" "${image}") # Verify mode never repairs an escaping/developer path.
    list(APPEND planned "${path}")
  endforeach()
  list(REMOVE_DUPLICATES planned)
  if(relocated)
    prove_qt_dependencies("${image}" "${arch}" "${planned}")
  endif()
  set(${output} "${planned}" PARENT_SCOPE)
endfunction()

file(GLOB_RECURSE candidates LIST_DIRECTORIES FALSE "${bundle}/*")
set(inspected)
set(macho_count 0)
foreach(candidate IN LISTS candidates)
  file(REAL_PATH "${candidate}" image)
  file(RELATIVE_PATH relative "${bundle}" "${image}")
  if(IS_ABSOLUTE "${relative}" OR relative MATCHES "^\\.\\.(/|$)")
    message(FATAL_ERROR "Package file symlink escapes bundle: ${candidate}")
  endif()
  if(image IN_LIST inspected)
    continue()
  endif()
  list(APPEND inspected "${image}")
  execute_process(COMMAND ${MACHO_FILE} -b "${image}" RESULT_VARIABLE result OUTPUT_VARIABLE kind)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Cannot inspect ${image}")
  endif()
  if(NOT kind MATCHES "Mach-O")
    continue()
  endif()
  math(EXPR macho_count "${macho_count} + 1")
  execute_process(COMMAND ${MACHO_LIPO} -archs "${image}"
    RESULT_VARIABLE result OUTPUT_VARIABLE architectures OUTPUT_STRIP_TRAILING_WHITESPACE)
  if(NOT result EQUAL 0 OR architectures STREQUAL "")
    message(FATAL_ERROR "Cannot enumerate Mach-O slices: ${image}")
  endif()
  separate_arguments(architectures UNIX_COMMAND "${architectures}")
  set(needs_dedupe FALSE)
  foreach(arch IN LISTS architectures)
    read_rpaths("${image}" "${arch}" original)
    plan_rpaths("${image}" "${arch}" "${original}" unique)
    if(NOT original STREQUAL unique)
      if(MODE STREQUAL "verify")
        message(FATAL_ERROR "Duplicate LC_RPATH in ${image} (${arch}): ${original}")
      endif()
      set(needs_dedupe TRUE)
    endif()
  endforeach()
  if(NOT needs_dedupe)
    continue()
  endif()
  string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
  set(work "${CMAKE_CURRENT_BINARY_DIR}/build-macos-rpaths-${nonce}")
  if(EXISTS "${work}")
    message(FATAL_ERROR "Temporary RPATH workspace already exists")
  endif()
  file(MAKE_DIRECTORY "${work}")
  list(LENGTH architectures arch_count)
  set(slices)
  foreach(arch IN LISTS architectures)
    set(slice "${work}/${arch}")
    if(arch_count EQUAL 1)
      file(COPY_FILE "${image}" "${slice}")
    else()
      execute_process(COMMAND ${MACHO_LIPO} -thin "${arch}" "${image}" -output "${slice}" RESULT_VARIABLE result)
      if(NOT result EQUAL 0)
        message(FATAL_ERROR "Cannot thin ${image} (${arch})")
      endif()
    endif()
    read_rpaths("${slice}" "${arch}" original)
    plan_rpaths("${image}" "${arch}" "${original}" unique)
    if(NOT original STREQUAL unique)
      file(CHMOD "${slice}" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
      # install_name_tool versions may delete one or all matching commands.
      # Remove the recorded commands with a finite bound, then restore the
      # ordered planned list: original distinct paths except proven SDK relocations.
      list(LENGTH original limit)
      set(remove "${original}")
      list(REMOVE_DUPLICATES remove)
      foreach(path IN LISTS remove)
        foreach(attempt RANGE 0 ${limit})
          read_rpaths("${slice}" "${arch}" current)
          if(NOT path IN_LIST current)
            break()
          endif()
          if(attempt EQUAL limit)
            message(FATAL_ERROR "LC_RPATH removal made no bounded progress")
          endif()
          execute_process(COMMAND ${MACHO_INSTALL_NAME_TOOL} -delete_rpath "${path}" "${slice}" RESULT_VARIABLE result)
          if(NOT result EQUAL 0)
            message(FATAL_ERROR "Cannot remove duplicate LC_RPATH in ${image} (${arch})")
          endif()
        endforeach()
      endforeach()
      foreach(path IN LISTS unique)
        execute_process(COMMAND ${MACHO_INSTALL_NAME_TOOL} -add_rpath "${path}" "${slice}" RESULT_VARIABLE result)
        if(NOT result EQUAL 0)
          message(FATAL_ERROR "Cannot restore LC_RPATH in ${image} (${arch})")
        endif()
      endforeach()
      read_rpaths("${slice}" "${arch}" restored)
      if(NOT restored STREQUAL unique)
        message(FATAL_ERROR "RPATH normalization changed planned paths/order in ${image} (${arch})")
      endif()
    endif()
    list(APPEND slices "${slice}")
  endforeach()
  if(arch_count EQUAL 1)
    list(GET slices 0 rebuilt)
  else()
    set(rebuilt "${work}/universal")
    execute_process(COMMAND ${MACHO_LIPO} -create ${slices} -output "${rebuilt}" RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
      message(FATAL_ERROR "Cannot reassemble ${image}")
    endif()
  endif()
  file(COPY_FILE "${rebuilt}" "${image}")
  file(REMOVE_RECURSE "${work}")
  message(STATUS "Normalized LC_RPATH (deduplication/proven Qt relocation): ${image}")
endforeach()
if(macho_count EQUAL 0)
  message(FATAL_ERROR "No Mach-O images found in ${bundle}")
endif()
message(STATUS "Mach-O RPATH ${MODE}: ${macho_count} images checked")
