cmake_minimum_required(VERSION 3.21)
# After macdeployqt/dylibbundler and before final signing. Only Mach-O images
# with duplicate LC_RPATHs are rewritten; every distinct path and its original
# search order are preserved. Fat slices are handled independently.
if(NOT MODE MATCHES "^(verify|dedupe)$" OR NOT IS_DIRECTORY "${BUNDLE_DIR}/Contents")
  message(FATAL_ERROR "Use -DMODE=verify|dedupe -DBUNDLE_DIR=/path/to/App.app")
endif()
foreach(tool FILE OTOOL LIPO INSTALL_NAME_TOOL)
  if(NOT DEFINED MACHO_${tool})
    string(TOLOWER "${tool}" name)
    find_program(MACHO_${tool} NAMES "${name}" REQUIRED)
  endif()
endforeach()
file(REAL_PATH "${BUNDLE_DIR}" bundle)
file(REAL_PATH "${bundle}/Contents" contents)

function(read_rpaths image arch output)
  execute_process(COMMAND ${MACHO_OTOOL} -arch "${arch}" -l "${image}"
    RESULT_VARIABLE result OUTPUT_VARIABLE listing ERROR_VARIABLE error)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "otool failed for ${image} (${arch}): ${error}")
  endif()
  string(REPLACE "\n" ";" lines "${listing}")
  set(paths)
  set(wanted FALSE)
  foreach(line IN LISTS lines)
    string(STRIP "${line}" line)
    if(line MATCHES "^cmd[ \t]+LC_RPATH$")
      set(wanted TRUE)
    elseif(wanted AND line MATCHES "^path (.*) \\(offset [0-9]+\\)$")
      list(APPEND paths "${CMAKE_MATCH_1}")
      set(wanted FALSE)
    endif()
  endforeach()
  if(wanted)
    message(FATAL_ERROR "Incomplete LC_RPATH in ${image} (${arch})")
  endif()
  set(${output} "${paths}" PARENT_SCOPE)
endfunction()

function(check_path path image)
  if(path MATCHES "^/System/Library(/|$)" OR path MATCHES "^/usr/lib(/|$)")
    return()
  elseif(path MATCHES "^@executable_path(/|$)")
    string(REGEX REPLACE "^@executable_path" "${contents}/MacOS" resolved "${path}")
  elseif(path MATCHES "^@loader_path(/|$)")
    get_filename_component(loader "${image}" DIRECTORY)
    string(REGEX REPLACE "^@loader_path" "${loader}" resolved "${path}")
  else()
    # Never hide a developer path by deleting it. Absolute paths into the
    # current staging tree are not relocatable either.
    message(FATAL_ERROR "Nonportable/developer LC_RPATH '${path}' in ${image}")
  endif()
  file(REAL_PATH "${resolved}" resolved)
  file(RELATIVE_PATH relative "${contents}" "${resolved}")
  if(IS_ABSOLUTE "${relative}" OR relative MATCHES "^\\.\\.(/|$)")
    message(FATAL_ERROR "LC_RPATH escapes actual package Contents: '${path}' in ${image}")
  endif()
endfunction()

file(GLOB_RECURSE candidates LIST_DIRECTORIES FALSE "${bundle}/*")
set(inspected)
set(macho_count 0)
foreach(candidate IN LISTS candidates)
  file(REAL_PATH "${candidate}" image)
  file(RELATIVE_PATH relative "${bundle}" "${image}")
  if(IS_ABSOLUTE "${relative}" OR relative MATCHES "^\\.\\.(/|$)")
    message(FATAL_ERROR "Package file symlink escapes bundle: ${candidate}")
  endif()
  if(image IN_LIST inspected)
    continue()
  endif()
  list(APPEND inspected "${image}")
  execute_process(COMMAND ${MACHO_FILE} -b "${image}" RESULT_VARIABLE result OUTPUT_VARIABLE kind)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Cannot inspect ${image}")
  endif()
  if(NOT kind MATCHES "Mach-O")
    continue()
  endif()
  math(EXPR macho_count "${macho_count} + 1")
  execute_process(COMMAND ${MACHO_LIPO} -archs "${image}"
    RESULT_VARIABLE result OUTPUT_VARIABLE architectures OUTPUT_STRIP_TRAILING_WHITESPACE)
  if(NOT result EQUAL 0 OR architectures STREQUAL "")
    message(FATAL_ERROR "Cannot enumerate Mach-O slices: ${image}")
  endif()
  separate_arguments(architectures UNIX_COMMAND "${architectures}")
  set(needs_dedupe FALSE)
  foreach(arch IN LISTS architectures)
    read_rpaths("${image}" "${arch}" original)
    set(unique "${original}")
    list(REMOVE_DUPLICATES unique)
    foreach(path IN LISTS unique)
      check_path("${path}" "${image}")
    endforeach()
    if(NOT original STREQUAL unique)
      if(MODE STREQUAL "verify")
        message(FATAL_ERROR "Duplicate LC_RPATH in ${image} (${arch}): ${original}")
      endif()
      set(needs_dedupe TRUE)
    endif()
  endforeach()
  if(NOT needs_dedupe)
    continue()
  endif()
  string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
  set(work "${CMAKE_CURRENT_BINARY_DIR}/build-macos-rpaths-${nonce}")
  if(EXISTS "${work}")
    message(FATAL_ERROR "Temporary RPATH workspace already exists")
  endif()
  file(MAKE_DIRECTORY "${work}")
  list(LENGTH architectures arch_count)
  set(slices)
  foreach(arch IN LISTS architectures)
    set(slice "${work}/${arch}")
    if(arch_count EQUAL 1)
      file(COPY_FILE "${image}" "${slice}")
    else()
      execute_process(COMMAND ${MACHO_LIPO} -thin "${arch}" "${image}" -output "${slice}" RESULT_VARIABLE result)
      if(NOT result EQUAL 0)
        message(FATAL_ERROR "Cannot thin ${image} (${arch})")
      endif()
    endif()
    read_rpaths("${slice}" "${arch}" original)
    set(unique "${original}")
    list(REMOVE_DUPLICATES unique)
    if(NOT original STREQUAL unique)
      file(CHMOD "${slice}" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
      # install_name_tool versions may delete one or all matching commands.
      # Remove the recorded commands with a finite bound, then restore the
      # ordered distinct ORIGINAL list, including every valid unique path.
      list(LENGTH original limit)
      foreach(path IN LISTS unique)
        foreach(attempt RANGE 0 ${limit})
          read_rpaths("${slice}" "${arch}" current)
          if(NOT path IN_LIST current)
            break()
          endif()
          if(attempt EQUAL limit)
            message(FATAL_ERROR "LC_RPATH removal made no bounded progress")
          endif()
          execute_process(COMMAND ${MACHO_INSTALL_NAME_TOOL} -delete_rpath "${path}" "${slice}" RESULT_VARIABLE result)
          if(NOT result EQUAL 0)
            message(FATAL_ERROR "Cannot remove duplicate LC_RPATH in ${image} (${arch})")
          endif()
        endforeach()
      endforeach()
      foreach(path IN LISTS unique)
        execute_process(COMMAND ${MACHO_INSTALL_NAME_TOOL} -add_rpath "${path}" "${slice}" RESULT_VARIABLE result)
        if(NOT result EQUAL 0)
          message(FATAL_ERROR "Cannot restore LC_RPATH in ${image} (${arch})")
        endif()
      endforeach()
      read_rpaths("${slice}" "${arch}" restored)
      if(NOT restored STREQUAL unique)
        message(FATAL_ERROR "RPATH deduplication changed needed paths/order in ${image} (${arch})")
      endif()
    endif()
    list(APPEND slices "${slice}")
  endforeach()
  if(arch_count EQUAL 1)
    list(GET slices 0 rebuilt)
  else()
    set(rebuilt "${work}/universal")
    execute_process(COMMAND ${MACHO_LIPO} -create ${slices} -output "${rebuilt}" RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
      message(FATAL_ERROR "Cannot reassemble ${image}")
    endif()
  endif()
  file(COPY_FILE "${rebuilt}" "${image}")
  file(REMOVE_RECURSE "${work}")
  message(STATUS "Deduplicated LC_RPATH: ${image}")
endforeach()
if(macho_count EQUAL 0)
  message(FATAL_ERROR "No Mach-O images found in ${bundle}")
endif()
message(STATUS "Mach-O RPATH ${MODE}: ${macho_count} images checked")
