cmake_minimum_required(VERSION 3.21)
include("${CMAKE_CURRENT_LIST_DIR}/../cmake/GaugeBundle.cmake")
if(NOT DEFINED BUNDLE_DIR OR BUNDLE_DIR STREQUAL "")
  message(FATAL_ERROR "BUNDLE_DIR is required")
endif()
if(MODE STREQUAL "verify")
  omatrack_verify_gauge_bundle("${BUNDLE_DIR}")
  message(STATUS "Offline model bundle: all 15 model/companion/notice files verified")
  return()
endif()
if(NOT MODE STREQUAL "fetch" AND NOT MODE STREQUAL "stage")
  message(FATAL_ERROR "MODE must be fetch, stage or verify")
endif()
omatrack_gauge_bundle_files(paths)
file(READ "${OMATRACK_GAUGE_BUNDLE_MANIFEST}" manifest)
string(JSON repository GET "${manifest}" repository)
string(JSON revision GET "${manifest}" revision)
string(LENGTH "${revision}" revision_length)
if(NOT repository STREQUAL "tobil/omatrack-telemetry-models" OR
   NOT revision MATCHES "^[0-9a-f]+$" OR NOT revision_length EQUAL 40)
  message(FATAL_ERROR "Bundle fetch requires the approved repository and immutable 40-hex revision")
endif()
if(MODE STREQUAL "stage")
  if(NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "Staging requires SOURCE_DIR")
  endif()
  omatrack_verify_gauge_bundle("${SOURCE_DIR}")
endif()
set(index 0)
foreach(path IN LISTS paths)
  string(JSON expected GET "${manifest}" files ${index} sha256)
  string(JSON bytes GET "${manifest}" files ${index} bytes)
  set(destination "${BUNDLE_DIR}/${path}")
  set(valid FALSE)
  if(EXISTS "${destination}" AND NOT IS_DIRECTORY "${destination}")
    file(SIZE "${destination}" actual_size)
    if(actual_size EQUAL bytes)
      file(SHA256 "${destination}" actual_hash)
      if(actual_hash STREQUAL expected)
        set(valid TRUE)
      endif()
    endif()
  endif()
  if(NOT valid)
    get_filename_component(parent "${destination}" DIRECTORY)
    file(MAKE_DIRECTORY "${parent}")
    string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
    set(temporary "${destination}.${nonce}.part")
    if(DEFINED SOURCE_DIR AND NOT SOURCE_DIR STREQUAL "")
      file(COPY_FILE "${SOURCE_DIR}/${path}" "${temporary}")
    else()
      # -q ignores curlrc; no credentials, cookies, telemetry, runtime fetch or
      # arbitrary manifest URLs. Bound both transfer size and duration.
      execute_process(COMMAND curl -q --fail --location --silent --show-error
        --proto "=https" --proto-redir "=https" --retry 2 --max-time 600
        --max-filesize "${bytes}"
        "https://huggingface.co/${repository}/resolve/${revision}/${path}"
        --output "${temporary}" RESULT_VARIABLE result)
      if(NOT result EQUAL 0)
        file(REMOVE "${temporary}")
        message(FATAL_ERROR "Pinned bundle download failed: ${path}")
      endif()
    endif()
    file(SIZE "${temporary}" actual_size)
    file(SHA256 "${temporary}" actual_hash)
    if(NOT actual_size EQUAL bytes OR NOT actual_hash STREQUAL expected)
      file(REMOVE "${temporary}")
      message(FATAL_ERROR "Pinned bundle size/SHA256 mismatch: ${path}")
    endif()
    file(RENAME "${temporary}" "${destination}")
  endif()
  math(EXPR index "${index} + 1")
endforeach()
file(COPY_FILE "${OMATRACK_GAUGE_BUNDLE_MANIFEST}" "${BUNDLE_DIR}/bundle.json" ONLY_IF_DIFFERENT)
omatrack_verify_gauge_bundle("${BUNDLE_DIR}")
message(STATUS "Offline model bundle: all 15 model/companion/notice files verified")
