# One app-owned allowlist for build-time downloads, staging and archive audits.
# The runtime's compiled per-candidate registry remains an independent gate.
set(OMATRACK_GAUGE_BUNDLE_MANIFEST "${CMAKE_CURRENT_LIST_DIR}/../models/bundle.json")

function(omatrack_gauge_bundle_files output)
  file(READ "${OMATRACK_GAUGE_BUNDLE_MANIFEST}" manifest)
  string(JSON schema GET "${manifest}" schema)
  if(NOT schema STREQUAL "omatrack-offline-model-bundle-v1")
    message(FATAL_ERROR "Unsupported offline model bundle manifest")
  endif()
  string(JSON count LENGTH "${manifest}" files)
  if(NOT count EQUAL 15)
    message(FATAL_ERROR "Offline bundle must contain only the 15 approved model/companion/notice files")
  endif()
  math(EXPR last "${count} - 1")
  set(paths)
  foreach(index RANGE 0 ${last})
    string(JSON path GET "${manifest}" files ${index} path)
    if(NOT path MATCHES "^[a-zA-Z0-9_./-]+$" OR path MATCHES "(^/|\\.\\.|//)")
      message(FATAL_ERROR "Unsafe model bundle path: ${path}")
    endif()
    if(path IN_LIST paths)
      message(FATAL_ERROR "Duplicate model bundle path: ${path}")
    endif()
    list(APPEND paths "${path}")
  endforeach()
  foreach(required gauge-reader.onnx
      detectors/tiny-v2/gauge-detector.onnx detectors/tiny-v2/metadata.json detectors/tiny-v2/contract.json
      detectors/aim-large-v1/gauge-detector.onnx detectors/aim-large-v1/metadata.json detectors/aim-large-v1/contract.json
      NOTICE.md README.md inventory.json licenses/reader/NOTICE licenses/reader/LICENSE-APACHE-2.0-UPSTREAM.txt
      licenses/reader/LICENSE-MIT-OMATRACK-CODE.txt licenses/detectors/NOTICE
      licenses/detectors/LICENSE-TORCHVISION-BSD-3-CLAUSE.txt)
    if(NOT required IN_LIST paths)
      message(FATAL_ERROR "Required model/notice missing from allowlist: ${required}")
    endif()
  endforeach()
  set(${output} "${paths}" PARENT_SCOPE)
endfunction()

function(omatrack_verify_gauge_bundle directory)
  omatrack_gauge_bundle_files(paths)
  file(READ "${OMATRACK_GAUGE_BUNDLE_MANIFEST}" manifest)
  set(index 0)
  foreach(path IN LISTS paths)
    string(JSON bytes GET "${manifest}" files ${index} bytes)
    string(JSON expected GET "${manifest}" files ${index} sha256)
    if(NOT EXISTS "${directory}/${path}" OR IS_DIRECTORY "${directory}/${path}")
      message(FATAL_ERROR "Offline model bundle missing ${path}")
    endif()
    file(SIZE "${directory}/${path}" actual_size)
    if(NOT actual_size EQUAL bytes)
      message(FATAL_ERROR "Offline bundle size mismatch: ${path}")
    endif()
    file(SHA256 "${directory}/${path}" actual)
    if(NOT actual STREQUAL expected)
      message(FATAL_ERROR "Offline bundle SHA256 mismatch: ${path}")
    endif()
    math(EXPR index "${index} + 1")
  endforeach()
  file(SHA256 "${OMATRACK_GAUGE_BUNDLE_MANIFEST}" expected_manifest)
  if(NOT EXISTS "${directory}/bundle.json")
    message(FATAL_ERROR "Installed model bundle manifest missing")
  endif()
  file(SHA256 "${directory}/bundle.json" actual_manifest)
  if(NOT actual_manifest STREQUAL expected_manifest)
    message(FATAL_ERROR "Installed model bundle manifest differs from pinned application manifest")
  endif()
endfunction()
